name: Build to aws ECR
on: push
jobs:
    login_to_aws:
        runs-on: ubuntu-latest
        steps:
            - name: Code Checkout
              uses: actions/checkout@v4

            - name: AWS LOGIN
              uses: aws-actions/configure-aws-credentials@v4.1.0
              with: 
                aws-region: ${{secrets.REGION}}
                aws-access-key-id: ${{secrets.ACCESS_KEY }}
                aws-secret-access-key: ${{secrets.SECRET_ACCESS_KEY}}
       